// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yunkcyzinqzyjwhodeea.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl1bmtjeXppbnF6eWp3aG9kZWVhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4Njc0MzAsImV4cCI6MjA2MTQ0MzQzMH0.aTmKq6ajjKOhEL7NAfoSC9r1PIrhjANWE_t-45oNfPU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);